package com.genorch.rag.retrieve;

import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;
import org.springframework.ai.document.Document;

import static org.assertj.core.api.Assertions.assertThat;

class RrfFusionTest {

    private Document doc(String id, String text) {
        return Document.builder().id(id).text(text).metadata(Map.of()).build();
    }

    @Test
    void autoGeneratedIdIsNonNull() {
        assertThat(new Document("text", Map.of()).getId()).isNotBlank();
    }

    @Test
    void fusesTwoRankedListsWithDedupAndRanking() {
        Document a = doc("a", "chunk A");
        Document b = doc("b", "chunk B");
        Document c = doc("c", "chunk C");

        List<Document> vector = List.of(a, b); // A rank1, B rank2
        List<Document> keyword = List.of(b, c); // B rank1, C rank2

        List<Document> fused = RrfFusion.fuse(List.of(vector, keyword), 60, 10);

        assertThat(fused).hasSize(3);
        // B appears in both lists -> highest fused score (1/61 + 1/62)
        assertThat(fused.get(0).getId()).isEqualTo("b");
        // A (rank1 in one list: 1/61) beats C (rank2 in one list: 1/62)
        assertThat(fused.get(1).getId()).isEqualTo("a");
        assertThat(fused.get(2).getId()).isEqualTo("c");
    }

    @Test
    void respectsTopN() {
        Document a = doc("a", "a");
        Document b = doc("b", "b");
        Document c = doc("c", "c");

        List<Document> fused = RrfFusion.fuse(List.of(List.of(a, b, c)), 60, 2);

        assertThat(fused).hasSize(2);
        assertThat(fused.get(0).getId()).isEqualTo("a");
        assertThat(fused.get(1).getId()).isEqualTo("b");
    }
}
